//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 11:06:22 AM CEST 
//


package es.securitasdirect.senales.model.cibb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EVENTS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EVENT">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ArmType">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ArmForced">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Zone">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="CancelPending">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="PanelInFault">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="EventType">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="DevIdentification">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="EventStatus">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ArmTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="DevManufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="MMV" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="Modelo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Counter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Ack" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="InsNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="InsNumber_e" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="DataTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="TypeProtocol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PROPS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="tfno" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                 &lt;attribute name="texto" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="pais" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="host" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="op" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="centro" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Numero" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="user" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="err" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="transId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="TimeIn" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                 &lt;attribute name="RecepName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Medio" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="TansmisionType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SeviceType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ProtocolType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="InOrOut" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DestinoType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="OrigenType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ModeloId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="origen" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Ok" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="ServiceType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "events",
    "props"
})
@XmlRootElement(name = "CIBB")
public class CIBB {

    @XmlElement(name = "EVENTS", required = true)
    protected CIBB.EVENTS events;
    @XmlElement(name = "PROPS", required = true)
    protected CIBB.PROPS props;

    /**
     * Gets the value of the events property.
     * 
     * @return
     *     possible object is
     *     {@link CIBB.EVENTS }
     *     
     */
    public CIBB.EVENTS getEVENTS() {
        return events;
    }

    /**
     * Sets the value of the events property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIBB.EVENTS }
     *     
     */
    public void setEVENTS(CIBB.EVENTS value) {
        this.events = value;
    }

    /**
     * Gets the value of the props property.
     * 
     * @return
     *     possible object is
     *     {@link CIBB.PROPS }
     *     
     */
    public CIBB.PROPS getPROPS() {
        return props;
    }

    /**
     * Sets the value of the props property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIBB.PROPS }
     *     
     */
    public void setPROPS(CIBB.PROPS value) {
        this.props = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EVENT">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ArmType">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ArmForced">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Zone">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="CancelPending">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="PanelInFault">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="EventType">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="DevIdentification">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="EventStatus">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ArmTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="DevManufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="MMV" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="Modelo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Counter" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Ack" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="InsNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="InsNumber_e" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="DataTime" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="TypeProtocol" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "event"
    })
    public static class EVENTS {

        @XmlElement(name = "EVENT", required = true)
        protected CIBB.EVENTS.EVENT event;
        @XmlAttribute(name = "MMV")
        protected Integer mmv;
        @XmlAttribute(name = "Modelo")
        protected String modelo;
        @XmlAttribute(name = "Counter")
        protected String counter;
        @XmlAttribute(name = "Ack")
        protected Integer ack;
        @XmlAttribute(name = "InsNumber")
        protected Integer insNumber;
        @XmlAttribute(name = "InsNumber_e")
        protected Integer insNumberE;
        @XmlAttribute(name = "DataTime")
        protected Integer dataTime;
        @XmlAttribute(name = "TypeProtocol")
        protected String typeProtocol;

        @Override
        public String toString() {
            final StringBuffer sb = new StringBuffer("EVENTS{");
            sb.append("event=").append(event);
            sb.append(", mmv=").append(mmv);
            sb.append(", modelo='").append(modelo).append('\'');
            sb.append(", counter='").append(counter).append('\'');
            sb.append(", ack=").append(ack);
            sb.append(", insNumber=").append(insNumber);
            sb.append(", insNumberE=").append(insNumberE);
            sb.append(", dataTime=").append(dataTime);
            sb.append(", typeProtocol='").append(typeProtocol).append('\'');
            sb.append('}');
            return sb.toString();
        }

        /**
         * Gets the value of the event property.
         * 
         * @return
         *     possible object is
         *     {@link CIBB.EVENTS.EVENT }
         *     
         */
        public CIBB.EVENTS.EVENT getEVENT() {
            return event;
        }

        /**
         * Sets the value of the event property.
         * 
         * @param value
         *     allowed object is
         *     {@link CIBB.EVENTS.EVENT }
         *     
         */
        public void setEVENT(CIBB.EVENTS.EVENT value) {
            this.event = value;
        }

        /**
         * Gets the value of the mmv property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMMV() {
            return mmv;
        }

        /**
         * Sets the value of the mmv property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMMV(Integer value) {
            this.mmv = value;
        }

        /**
         * Gets the value of the modelo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModelo() {
            return modelo;
        }

        /**
         * Sets the value of the modelo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModelo(String value) {
            this.modelo = value;
        }

        /**
         * Gets the value of the counter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCounter() {
            return counter;
        }

        /**
         * Sets the value of the counter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCounter(String value) {
            this.counter = value;
        }

        /**
         * Gets the value of the ack property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getAck() {
            return ack;
        }

        /**
         * Sets the value of the ack property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setAck(Integer value) {
            this.ack = value;
        }

        /**
         * Gets the value of the insNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getInsNumber() {
            return insNumber;
        }

        /**
         * Sets the value of the insNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setInsNumber(Integer value) {
            this.insNumber = value;
        }

        /**
         * Gets the value of the insNumberE property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getInsNumberE() {
            return insNumberE;
        }

        /**
         * Sets the value of the insNumberE property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setInsNumberE(Integer value) {
            this.insNumberE = value;
        }

        /**
         * Gets the value of the dataTime property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getDataTime() {
            return dataTime;
        }

        /**
         * Sets the value of the dataTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setDataTime(Integer value) {
            this.dataTime = value;
        }

        /**
         * Gets the value of the typeProtocol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypeProtocol() {
            return typeProtocol;
        }

        /**
         * Sets the value of the typeProtocol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypeProtocol(String value) {
            this.typeProtocol = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ArmType">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ArmForced">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Zone">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="CancelPending">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="PanelInFault">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="EventType">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="DevIdentification">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="EventStatus">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ArmTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="DevManufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "type",
            "armType",
            "armForced",
            "zone",
            "cancelPending",
            "panelInFault",
            "eventType",
            "devIdentification",
            "eventStatus",
            "armTime",
            "devManufacturer"
        })
        public static class EVENT {

            protected int type;
            @XmlElement(name = "ArmType", required = true)
            protected CIBB.EVENTS.EVENT.ArmType armType;
            @XmlElement(name = "ArmForced", required = true)
            protected CIBB.EVENTS.EVENT.ArmForced armForced;
            @XmlElement(name = "Zone", required = true)
            protected CIBB.EVENTS.EVENT.Zone zone;
            @XmlElement(name = "CancelPending", required = true)
            protected CIBB.EVENTS.EVENT.CancelPending cancelPending;
            @XmlElement(name = "PanelInFault", required = true)
            protected CIBB.EVENTS.EVENT.PanelInFault panelInFault;
            @XmlElement(name = "EventType", required = true)
            protected CIBB.EVENTS.EVENT.EventType eventType;
            @XmlElement(name = "DevIdentification", required = true)
            protected CIBB.EVENTS.EVENT.DevIdentification devIdentification;
            @XmlElement(name = "EventStatus", required = true)
            protected CIBB.EVENTS.EVENT.EventStatus eventStatus;
            @XmlElement(name = "ArmTime")
            protected int armTime;
            @XmlElement(name = "DevManufacturer", required = true)
            protected String devManufacturer;
            @XmlAttribute
            protected String id;

            /**
             * Gets the value of the type property.
             * 
             */
            public int getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             */
            public void setType(int value) {
                this.type = value;
            }

            /**
             * Gets the value of the armType property.
             * 
             * @return
             *     possible object is
             *     {@link CIBB.EVENTS.EVENT.ArmType }
             *     
             */
            public CIBB.EVENTS.EVENT.ArmType getArmType() {
                return armType;
            }

            /**
             * Sets the value of the armType property.
             * 
             * @param value
             *     allowed object is
             *     {@link CIBB.EVENTS.EVENT.ArmType }
             *     
             */
            public void setArmType(CIBB.EVENTS.EVENT.ArmType value) {
                this.armType = value;
            }

            /**
             * Gets the value of the armForced property.
             * 
             * @return
             *     possible object is
             *     {@link CIBB.EVENTS.EVENT.ArmForced }
             *     
             */
            public CIBB.EVENTS.EVENT.ArmForced getArmForced() {
                return armForced;
            }

            /**
             * Sets the value of the armForced property.
             * 
             * @param value
             *     allowed object is
             *     {@link CIBB.EVENTS.EVENT.ArmForced }
             *     
             */
            public void setArmForced(CIBB.EVENTS.EVENT.ArmForced value) {
                this.armForced = value;
            }

            /**
             * Gets the value of the zone property.
             * 
             * @return
             *     possible object is
             *     {@link CIBB.EVENTS.EVENT.Zone }
             *     
             */
            public CIBB.EVENTS.EVENT.Zone getZone() {
                return zone;
            }

            /**
             * Sets the value of the zone property.
             * 
             * @param value
             *     allowed object is
             *     {@link CIBB.EVENTS.EVENT.Zone }
             *     
             */
            public void setZone(CIBB.EVENTS.EVENT.Zone value) {
                this.zone = value;
            }

            /**
             * Gets the value of the cancelPending property.
             * 
             * @return
             *     possible object is
             *     {@link CIBB.EVENTS.EVENT.CancelPending }
             *     
             */
            public CIBB.EVENTS.EVENT.CancelPending getCancelPending() {
                return cancelPending;
            }

            /**
             * Sets the value of the cancelPending property.
             * 
             * @param value
             *     allowed object is
             *     {@link CIBB.EVENTS.EVENT.CancelPending }
             *     
             */
            public void setCancelPending(CIBB.EVENTS.EVENT.CancelPending value) {
                this.cancelPending = value;
            }

            /**
             * Gets the value of the panelInFault property.
             * 
             * @return
             *     possible object is
             *     {@link CIBB.EVENTS.EVENT.PanelInFault }
             *     
             */
            public CIBB.EVENTS.EVENT.PanelInFault getPanelInFault() {
                return panelInFault;
            }

            /**
             * Sets the value of the panelInFault property.
             * 
             * @param value
             *     allowed object is
             *     {@link CIBB.EVENTS.EVENT.PanelInFault }
             *     
             */
            public void setPanelInFault(CIBB.EVENTS.EVENT.PanelInFault value) {
                this.panelInFault = value;
            }

            /**
             * Gets the value of the eventType property.
             * 
             * @return
             *     possible object is
             *     {@link CIBB.EVENTS.EVENT.EventType }
             *     
             */
            public CIBB.EVENTS.EVENT.EventType getEventType() {
                return eventType;
            }

            /**
             * Sets the value of the eventType property.
             * 
             * @param value
             *     allowed object is
             *     {@link CIBB.EVENTS.EVENT.EventType }
             *     
             */
            public void setEventType(CIBB.EVENTS.EVENT.EventType value) {
                this.eventType = value;
            }

            /**
             * Gets the value of the devIdentification property.
             * 
             * @return
             *     possible object is
             *     {@link CIBB.EVENTS.EVENT.DevIdentification }
             *     
             */
            public CIBB.EVENTS.EVENT.DevIdentification getDevIdentification() {
                return devIdentification;
            }

            /**
             * Sets the value of the devIdentification property.
             * 
             * @param value
             *     allowed object is
             *     {@link CIBB.EVENTS.EVENT.DevIdentification }
             *     
             */
            public void setDevIdentification(CIBB.EVENTS.EVENT.DevIdentification value) {
                this.devIdentification = value;
            }

            /**
             * Gets the value of the eventStatus property.
             * 
             * @return
             *     possible object is
             *     {@link CIBB.EVENTS.EVENT.EventStatus }
             *     
             */
            public CIBB.EVENTS.EVENT.EventStatus getEventStatus() {
                return eventStatus;
            }

            /**
             * Sets the value of the eventStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link CIBB.EVENTS.EVENT.EventStatus }
             *     
             */
            public void setEventStatus(CIBB.EVENTS.EVENT.EventStatus value) {
                this.eventStatus = value;
            }

            /**
             * Gets the value of the armTime property.
             * 
             */
            public int getArmTime() {
                return armTime;
            }

            /**
             * Sets the value of the armTime property.
             * 
             */
            public void setArmTime(int value) {
                this.armTime = value;
            }

            /**
             * Gets the value of the devManufacturer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDevManufacturer() {
                return devManufacturer;
            }

            /**
             * Sets the value of the devManufacturer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDevManufacturer(String value) {
                this.devManufacturer = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class ArmForced {

                @XmlAttribute
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class ArmType {

                @XmlAttribute
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class CancelPending {

                @XmlAttribute
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class DevIdentification {

                @XmlAttribute
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class EventStatus {

                @XmlAttribute
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class EventType {

                @XmlAttribute
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class PanelInFault {

                @XmlAttribute
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Zone {

                @XmlAttribute
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="tfno" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *       &lt;attribute name="texto" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="pais" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="host" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="op" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="centro" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Numero" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="user" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="err" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="transId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="TimeIn" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *       &lt;attribute name="RecepName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Medio" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="TansmisionType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SeviceType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ProtocolType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="InOrOut" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="DestinoType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="OrigenType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ModeloId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="origen" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Ok" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="ServiceType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PROPS {

        @XmlAttribute
        protected BigDecimal tfno;
        @XmlAttribute
        protected String texto;
        @XmlAttribute
        protected String pais;
        @XmlAttribute
        protected String host;
        @XmlAttribute
        protected String op;
        @XmlAttribute
        protected String centro;
        @XmlAttribute(name = "Numero")
        protected String numero;
        @XmlAttribute
        protected String tipo;
        @XmlAttribute
        protected Integer user;
        @XmlAttribute
        protected String err;
        @XmlAttribute
        protected String transId;
        @XmlAttribute(name = "TimeIn")
        protected BigDecimal timeIn;
        @XmlAttribute(name = "RecepName")
        protected String recepName;
        @XmlAttribute(name = "Medio")
        protected String medio;
        @XmlAttribute(name = "TansmisionType")
        protected String tansmisionType;
        @XmlAttribute(name = "SeviceType")
        protected String seviceType;
        @XmlAttribute(name = "ProtocolType")
        protected String protocolType;
        @XmlAttribute(name = "InOrOut")
        protected String inOrOut;
        @XmlAttribute(name = "DestinoType")
        protected String destinoType;
        @XmlAttribute(name = "OrigenType")
        protected String origenType;
        @XmlAttribute(name = "ModeloId")
        protected String modeloId;
        @XmlAttribute
        protected String origen;
        @XmlAttribute(name = "Ok")
        protected Boolean ok;
        @XmlAttribute(name = "ServiceType")
        protected String serviceType;

        @Override
        public String toString() {
            final StringBuffer sb = new StringBuffer("PROPS{");
            sb.append("tfno=").append(tfno);
            sb.append(", texto='").append(texto).append('\'');
            sb.append(", pais='").append(pais).append('\'');
            sb.append(", host='").append(host).append('\'');
            sb.append(", op='").append(op).append('\'');
            sb.append(", centro='").append(centro).append('\'');
            sb.append(", numero='").append(numero).append('\'');
            sb.append(", tipo='").append(tipo).append('\'');
            sb.append(", user=").append(user);
            sb.append(", err='").append(err).append('\'');
            sb.append(", transId='").append(transId).append('\'');
            sb.append(", timeIn=").append(timeIn);
            sb.append(", recepName='").append(recepName).append('\'');
            sb.append(", medio='").append(medio).append('\'');
            sb.append(", tansmisionType='").append(tansmisionType).append('\'');
            sb.append(", seviceType='").append(seviceType).append('\'');
            sb.append(", protocolType='").append(protocolType).append('\'');
            sb.append(", inOrOut='").append(inOrOut).append('\'');
            sb.append(", destinoType='").append(destinoType).append('\'');
            sb.append(", origenType='").append(origenType).append('\'');
            sb.append(", modeloId='").append(modeloId).append('\'');
            sb.append(", origen='").append(origen).append('\'');
            sb.append(", ok=").append(ok);
            sb.append(", serviceType='").append(serviceType).append('\'');
            sb.append('}');
            return sb.toString();
        }

        /**
         * Gets the value of the tfno property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTfno() {
            return tfno;
        }

        /**
         * Sets the value of the tfno property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTfno(BigDecimal value) {
            this.tfno = value;
        }

        /**
         * Gets the value of the texto property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTexto() {
            return texto;
        }

        /**
         * Sets the value of the texto property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTexto(String value) {
            this.texto = value;
        }

        /**
         * Gets the value of the pais property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPais() {
            return pais;
        }

        /**
         * Sets the value of the pais property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPais(String value) {
            this.pais = value;
        }

        /**
         * Gets the value of the host property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHost() {
            return host;
        }

        /**
         * Sets the value of the host property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHost(String value) {
            this.host = value;
        }

        /**
         * Gets the value of the op property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOp() {
            return op;
        }

        /**
         * Sets the value of the op property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOp(String value) {
            this.op = value;
        }

        /**
         * Gets the value of the centro property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCentro() {
            return centro;
        }

        /**
         * Sets the value of the centro property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCentro(String value) {
            this.centro = value;
        }

        /**
         * Gets the value of the numero property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumero() {
            return numero;
        }

        /**
         * Sets the value of the numero property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumero(String value) {
            this.numero = value;
        }

        /**
         * Gets the value of the tipo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipo() {
            return tipo;
        }

        /**
         * Sets the value of the tipo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipo(String value) {
            this.tipo = value;
        }

        /**
         * Gets the value of the user property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUser() {
            return user;
        }

        /**
         * Sets the value of the user property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUser(Integer value) {
            this.user = value;
        }

        /**
         * Gets the value of the err property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErr() {
            return err;
        }

        /**
         * Sets the value of the err property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErr(String value) {
            this.err = value;
        }

        /**
         * Gets the value of the transId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransId() {
            return transId;
        }

        /**
         * Sets the value of the transId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransId(String value) {
            this.transId = value;
        }

        /**
         * Gets the value of the timeIn property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTimeIn() {
            return timeIn;
        }

        /**
         * Sets the value of the timeIn property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTimeIn(BigDecimal value) {
            this.timeIn = value;
        }

        /**
         * Gets the value of the recepName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecepName() {
            return recepName;
        }

        /**
         * Sets the value of the recepName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecepName(String value) {
            this.recepName = value;
        }

        /**
         * Gets the value of the medio property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMedio() {
            return medio;
        }

        /**
         * Sets the value of the medio property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMedio(String value) {
            this.medio = value;
        }

        /**
         * Gets the value of the tansmisionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTansmisionType() {
            return tansmisionType;
        }

        /**
         * Sets the value of the tansmisionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTansmisionType(String value) {
            this.tansmisionType = value;
        }

        /**
         * Gets the value of the seviceType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeviceType() {
            return seviceType;
        }

        /**
         * Sets the value of the seviceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeviceType(String value) {
            this.seviceType = value;
        }

        /**
         * Gets the value of the protocolType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProtocolType() {
            return protocolType;
        }

        /**
         * Sets the value of the protocolType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProtocolType(String value) {
            this.protocolType = value;
        }

        /**
         * Gets the value of the inOrOut property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInOrOut() {
            return inOrOut;
        }

        /**
         * Sets the value of the inOrOut property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInOrOut(String value) {
            this.inOrOut = value;
        }

        /**
         * Gets the value of the destinoType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestinoType() {
            return destinoType;
        }

        /**
         * Sets the value of the destinoType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestinoType(String value) {
            this.destinoType = value;
        }

        /**
         * Gets the value of the origenType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigenType() {
            return origenType;
        }

        /**
         * Sets the value of the origenType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigenType(String value) {
            this.origenType = value;
        }

        /**
         * Gets the value of the modeloId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModeloId() {
            return modeloId;
        }

        /**
         * Sets the value of the modeloId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModeloId(String value) {
            this.modeloId = value;
        }

        /**
         * Gets the value of the origen property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigen() {
            return origen;
        }

        /**
         * Sets the value of the origen property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigen(String value) {
            this.origen = value;
        }

        /**
         * Gets the value of the ok property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isOk() {
            return ok;
        }

        /**
         * Sets the value of the ok property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOk(Boolean value) {
            this.ok = value;
        }

        /**
         * Gets the value of the serviceType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServiceType() {
            return serviceType;
        }

        /**
         * Sets the value of the serviceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServiceType(String value) {
            this.serviceType = value;
        }

    }


    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("CIBB{");
        sb.append("events=").append(events);
        sb.append(", props=").append(props);
        sb.append('}');
        return sb.toString();
    }
}
