//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 11:06:22 AM CEST 
//


package es.securitasdirect.senales.model.cibb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.securitasdirect.senales.model.cibb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.securitasdirect.senales.model.cibb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CIBB.EVENTS.EVENT.PanelInFault }
     * 
     */
    public CIBB.EVENTS.EVENT.PanelInFault createCIBBEVENTSEVENTPanelInFault() {
        return new CIBB.EVENTS.EVENT.PanelInFault();
    }

    /**
     * Create an instance of {@link CIBB.EVENTS.EVENT.CancelPending }
     * 
     */
    public CIBB.EVENTS.EVENT.CancelPending createCIBBEVENTSEVENTCancelPending() {
        return new CIBB.EVENTS.EVENT.CancelPending();
    }

    /**
     * Create an instance of {@link CIBB.PROPS }
     * 
     */
    public CIBB.PROPS createCIBBPROPS() {
        return new CIBB.PROPS();
    }

    /**
     * Create an instance of {@link CIBB }
     * 
     */
    public CIBB createCIBB() {
        return new CIBB();
    }

    /**
     * Create an instance of {@link CIBB.EVENTS.EVENT.EventStatus }
     * 
     */
    public CIBB.EVENTS.EVENT.EventStatus createCIBBEVENTSEVENTEventStatus() {
        return new CIBB.EVENTS.EVENT.EventStatus();
    }

    /**
     * Create an instance of {@link CIBB.EVENTS.EVENT.EventType }
     * 
     */
    public CIBB.EVENTS.EVENT.EventType createCIBBEVENTSEVENTEventType() {
        return new CIBB.EVENTS.EVENT.EventType();
    }

    /**
     * Create an instance of {@link CIBB.EVENTS.EVENT.ArmType }
     * 
     */
    public CIBB.EVENTS.EVENT.ArmType createCIBBEVENTSEVENTArmType() {
        return new CIBB.EVENTS.EVENT.ArmType();
    }

    /**
     * Create an instance of {@link CIBB.EVENTS.EVENT.DevIdentification }
     * 
     */
    public CIBB.EVENTS.EVENT.DevIdentification createCIBBEVENTSEVENTDevIdentification() {
        return new CIBB.EVENTS.EVENT.DevIdentification();
    }

    /**
     * Create an instance of {@link CIBB.EVENTS.EVENT.Zone }
     * 
     */
    public CIBB.EVENTS.EVENT.Zone createCIBBEVENTSEVENTZone() {
        return new CIBB.EVENTS.EVENT.Zone();
    }

    /**
     * Create an instance of {@link CIBB.EVENTS.EVENT.ArmForced }
     * 
     */
    public CIBB.EVENTS.EVENT.ArmForced createCIBBEVENTSEVENTArmForced() {
        return new CIBB.EVENTS.EVENT.ArmForced();
    }

    /**
     * Create an instance of {@link CIBB.EVENTS.EVENT }
     * 
     */
    public CIBB.EVENTS.EVENT createCIBBEVENTSEVENT() {
        return new CIBB.EVENTS.EVENT();
    }

    /**
     * Create an instance of {@link CIBB.EVENTS }
     * 
     */
    public CIBB.EVENTS createCIBBEVENTS() {
        return new CIBB.EVENTS();
    }

}
