//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.25 at 10:59:55 AM CEST 
//


package es.securitasdirect.tareas.model.tickets.responses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.securitasdirect.tareas.model.tickets.responses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.securitasdirect.tareas.model.tickets.responses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DATA.ERR }
     * 
     */
    public DATA.ERR createDATAERR() {
        return new DATA.ERR();
    }

    /**
     * Create an instance of {@link DATA }
     * 
     */
    public DATA createDATA() {
        return new DATA();
    }

    /**
     * Create an instance of {@link DATA.ERR.UPDATE }
     * 
     */
    public DATA.ERR.UPDATE createDATAERRUPDATE() {
        return new DATA.ERR.UPDATE();
    }

    /**
     * Create an instance of {@link DATA.TICKET }
     * 
     */
    public DATA.TICKET createDATATICKET() {
        return new DATA.TICKET();
    }

    /**
     * Create an instance of {@link DATA.SREQ }
     * 
     */
    public DATA.SREQ createDATASREQ() {
        return new DATA.SREQ();
    }

}
