//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.24 at 01:29:08 PM CEST 
//


package es.securitasdirect.tareas.model.tickets.operations;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.securitasdirect.tareas.model.tickets.operations package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.securitasdirect.tareas.model.tickets.operations
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DATA.TICKET }
     * 
     */
    public DATA.TICKET createDATATICKET() {
        return new DATA.TICKET();
    }

    /**
     * Create an instance of {@link DATA.TICKET.CLCOD }
     * 
     */
    public DATA.TICKET.CLCOD createDATATICKETCLCOD() {
        return new DATA.TICKET.CLCOD();
    }

    /**
     * Create an instance of {@link DATA.TICKET.CONTACTO }
     * 
     */
    public DATA.TICKET.CONTACTO createDATATICKETCONTACTO() {
        return new DATA.TICKET.CONTACTO();
    }

    /**
     * Create an instance of {@link DATA.TICKET.REQ }
     * 
     */
    public DATA.TICKET.REQ createDATATICKETREQ() {
        return new DATA.TICKET.REQ();
    }

    /**
     * Create an instance of {@link DATA.SVRQ.ITEMS }
     * 
     */
    public DATA.SVRQ.ITEMS createDATASVRQITEMS() {
        return new DATA.SVRQ.ITEMS();
    }

    /**
     * Create an instance of {@link DATA }
     * 
     */
    public DATA createDATA() {
        return new DATA();
    }

    /**
     * Create an instance of {@link DATA.USER }
     * 
     */
    public DATA.USER createDATAUSER() {
        return new DATA.USER();
    }

    /**
     * Create an instance of {@link DATA.SVRQ.ITEMS.Item }
     * 
     */
    public DATA.SVRQ.ITEMS.Item createDATASVRQITEMSItem() {
        return new DATA.SVRQ.ITEMS.Item();
    }

    /**
     * Create an instance of {@link DATA.SVRQ }
     * 
     */
    public DATA.SVRQ createDATASVRQ() {
        return new DATA.SVRQ();
    }

    /**
     * Create an instance of {@link DATA.TICKET.ASGTO }
     * 
     */
    public DATA.TICKET.ASGTO createDATATICKETASGTO() {
        return new DATA.TICKET.ASGTO();
    }

    /**
     * Create an instance of {@link DATA.TICKET.CLOSE }
     * 
     */
    public DATA.TICKET.CLOSE createDATATICKETCLOSE() {
        return new DATA.TICKET.CLOSE();
    }

    /**
     * Create an instance of {@link DATA.TICKET.CODIFICATIONS.CODIF }
     * 
     */
    public DATA.TICKET.CODIFICATIONS.CODIF createDATATICKETCODIFICATIONSCODIF() {
        return new DATA.TICKET.CODIFICATIONS.CODIF();
    }

    /**
     * Create an instance of {@link DATA.TICKET.CODIFICATIONS }
     * 
     */
    public DATA.TICKET.CODIFICATIONS createDATATICKETCODIFICATIONS() {
        return new DATA.TICKET.CODIFICATIONS();
    }

    /**
     * Create an instance of {@link DATA.TICKET.COMM }
     * 
     */
    public DATA.TICKET.COMM createDATATICKETCOMM() {
        return new DATA.TICKET.COMM();
    }

    /**
     * Create an instance of {@link DATA.TICKET.OPCOD }
     * 
     */
    public DATA.TICKET.OPCOD createDATATICKETOPCOD() {
        return new DATA.TICKET.OPCOD();
    }

}
