//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.24 at 10:57:59 AM CEST 
//


package es.securitasdirect.tareas.model.tickets.operations;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="USER">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="idUser" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="idCountry" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="idLanguage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="t" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TICKET">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="REQ">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="idReq" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="reqName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="reqLname1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="reqLname2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="reqCif" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="reqEmpl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ASGTO">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="idAsg" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="idUser" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="COMM">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="lName1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="lName2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="inChannel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="coment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="outChannel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="to" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="OPCOD">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="codKey1" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="codKey2" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CLCOD">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="codKey3" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="codKey4" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="numInst" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="observ" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="codZIP" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="closeTicket" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="dataAditional" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="noteClose" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="morDebt" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="typePanel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SVRQ">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ITEMS">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="item" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="idType" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="idProblem" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="idItemIBS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="makeSVRQ" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="idTec" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="insBoli" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CONTACTO">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="nombre" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="codforma" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="desde" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="hasta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="valor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="comentario" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CODIFICATIONS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CODIF" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="idType" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="idProblem" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CLOSE">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="closeTicket" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="dataAditional" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="notaCierre" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "user",
    "ticket",
    "svrq",
    "contacto",
    "codifications",
    "close"
})
@XmlRootElement(name = "DATA")
public class OperateTicket {

    @XmlElement(name = "USER", required = true)
    protected OperateTicket.USER user;
    @XmlElement(name = "TICKET", required = true)
    protected OperateTicket.TICKET ticket;
    @XmlElement(name = "SVRQ", required = true)
    protected OperateTicket.SVRQ svrq;
    @XmlElement(name = "CONTACTO", required = true)
    protected OperateTicket.CONTACTO contacto;
    @XmlElement(name = "CODIFICATIONS", required = true)
    protected OperateTicket.CODIFICATIONS codifications;
    @XmlElement(name = "CLOSE", required = true)
    protected OperateTicket.CLOSE close;

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link OperateTicket.USER }
     *     
     */
    public OperateTicket.USER getUSER() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperateTicket.USER }
     *     
     */
    public void setUSER(OperateTicket.USER value) {
        this.user = value;
    }

    /**
     * Gets the value of the ticket property.
     * 
     * @return
     *     possible object is
     *     {@link OperateTicket.TICKET }
     *     
     */
    public OperateTicket.TICKET getTICKET() {
        return ticket;
    }

    /**
     * Sets the value of the ticket property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperateTicket.TICKET }
     *     
     */
    public void setTICKET(OperateTicket.TICKET value) {
        this.ticket = value;
    }

    /**
     * Gets the value of the svrq property.
     * 
     * @return
     *     possible object is
     *     {@link OperateTicket.SVRQ }
     *     
     */
    public OperateTicket.SVRQ getSVRQ() {
        return svrq;
    }

    /**
     * Sets the value of the svrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperateTicket.SVRQ }
     *     
     */
    public void setSVRQ(OperateTicket.SVRQ value) {
        this.svrq = value;
    }

    /**
     * Gets the value of the contacto property.
     * 
     * @return
     *     possible object is
     *     {@link OperateTicket.CONTACTO }
     *     
     */
    public OperateTicket.CONTACTO getCONTACTO() {
        return contacto;
    }

    /**
     * Sets the value of the contacto property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperateTicket.CONTACTO }
     *     
     */
    public void setCONTACTO(OperateTicket.CONTACTO value) {
        this.contacto = value;
    }

    /**
     * Gets the value of the codifications property.
     * 
     * @return
     *     possible object is
     *     {@link OperateTicket.CODIFICATIONS }
     *     
     */
    public OperateTicket.CODIFICATIONS getCODIFICATIONS() {
        return codifications;
    }

    /**
     * Sets the value of the codifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperateTicket.CODIFICATIONS }
     *     
     */
    public void setCODIFICATIONS(OperateTicket.CODIFICATIONS value) {
        this.codifications = value;
    }

    /**
     * Gets the value of the close property.
     * 
     * @return
     *     possible object is
     *     {@link OperateTicket.CLOSE }
     *     
     */
    public OperateTicket.CLOSE getCLOSE() {
        return close;
    }

    /**
     * Sets the value of the close property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperateTicket.CLOSE }
     *     
     */
    public void setCLOSE(OperateTicket.CLOSE value) {
        this.close = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="closeTicket" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="dataAditional" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="notaCierre" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CLOSE {

        @XmlAttribute
        protected Integer closeTicket;
        @XmlAttribute
        protected String dataAditional;
        @XmlAttribute
        protected String notaCierre;

        /**
         * Gets the value of the closeTicket property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCloseTicket() {
            return closeTicket;
        }

        /**
         * Sets the value of the closeTicket property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCloseTicket(Integer value) {
            this.closeTicket = value;
        }

        /**
         * Gets the value of the dataAditional property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDataAditional() {
            return dataAditional;
        }

        /**
         * Sets the value of the dataAditional property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataAditional(String value) {
            this.dataAditional = value;
        }

        /**
         * Gets the value of the notaCierre property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotaCierre() {
            return notaCierre;
        }

        /**
         * Sets the value of the notaCierre property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotaCierre(String value) {
            this.notaCierre = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CODIF" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="idType" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="idProblem" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "codif"
    })
    public static class CODIFICATIONS {

        @XmlElement(name = "CODIF", required = true)
        protected List<OperateTicket.CODIFICATIONS.CODIF> codif;

        /**
         * Gets the value of the codif property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the codif property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCODIF().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OperateTicket.CODIFICATIONS.CODIF }
         * 
         * 
         */
        public List<OperateTicket.CODIFICATIONS.CODIF> getCODIF() {
            if (codif == null) {
                codif = new ArrayList<OperateTicket.CODIFICATIONS.CODIF>();
            }
            return this.codif;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="idType" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="idProblem" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CODIF {

            @XmlAttribute
            protected Integer idType;
            @XmlAttribute
            protected Integer idProblem;
            @XmlAttribute
            protected Integer count;

            /**
             * Gets the value of the idType property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getIdType() {
                return idType;
            }

            /**
             * Sets the value of the idType property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setIdType(Integer value) {
                this.idType = value;
            }

            /**
             * Gets the value of the idProblem property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getIdProblem() {
                return idProblem;
            }

            /**
             * Sets the value of the idProblem property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setIdProblem(Integer value) {
                this.idProblem = value;
            }

            /**
             * Gets the value of the count property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getCount() {
                return count;
            }

            /**
             * Sets the value of the count property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setCount(Integer value) {
                this.count = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="nombre" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="codforma" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="desde" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="hasta" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="valor" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="comentario" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CONTACTO {

        @XmlAttribute
        protected String nombre;
        @XmlAttribute
        protected String codforma;
        @XmlAttribute
        protected String desde;
        @XmlAttribute
        protected String hasta;
        @XmlAttribute
        protected String valor;
        @XmlAttribute
        protected String comentario;

        /**
         * Gets the value of the nombre property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombre() {
            return nombre;
        }

        /**
         * Sets the value of the nombre property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombre(String value) {
            this.nombre = value;
        }

        /**
         * Gets the value of the codforma property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodforma() {
            return codforma;
        }

        /**
         * Sets the value of the codforma property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodforma(String value) {
            this.codforma = value;
        }

        /**
         * Gets the value of the desde property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesde() {
            return desde;
        }

        /**
         * Sets the value of the desde property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesde(String value) {
            this.desde = value;
        }

        /**
         * Gets the value of the hasta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHasta() {
            return hasta;
        }

        /**
         * Sets the value of the hasta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHasta(String value) {
            this.hasta = value;
        }

        /**
         * Gets the value of the valor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValor() {
            return valor;
        }

        /**
         * Sets the value of the valor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValor(String value) {
            this.valor = value;
        }

        /**
         * Gets the value of the comentario property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComentario() {
            return comentario;
        }

        /**
         * Sets the value of the comentario property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComentario(String value) {
            this.comentario = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ITEMS">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="item" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="idType" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="idProblem" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="idItemIBS" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="makeSVRQ" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="idTec" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="insBoli" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "items"
    })
    public static class SVRQ {

        @XmlElement(name = "ITEMS", required = true)
        protected OperateTicket.SVRQ.ITEMS items;
        @XmlAttribute
        protected Integer makeSVRQ;
        @XmlAttribute
        protected String idTec;
        @XmlAttribute
        protected Integer insBoli;

        /**
         * Gets the value of the items property.
         * 
         * @return
         *     possible object is
         *     {@link OperateTicket.SVRQ.ITEMS }
         *     
         */
        public OperateTicket.SVRQ.ITEMS getITEMS() {
            return items;
        }

        /**
         * Sets the value of the items property.
         * 
         * @param value
         *     allowed object is
         *     {@link OperateTicket.SVRQ.ITEMS }
         *     
         */
        public void setITEMS(OperateTicket.SVRQ.ITEMS value) {
            this.items = value;
        }

        /**
         * Gets the value of the makeSVRQ property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMakeSVRQ() {
            return makeSVRQ;
        }

        /**
         * Sets the value of the makeSVRQ property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMakeSVRQ(Integer value) {
            this.makeSVRQ = value;
        }

        /**
         * Gets the value of the idTec property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdTec() {
            return idTec;
        }

        /**
         * Sets the value of the idTec property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdTec(String value) {
            this.idTec = value;
        }

        /**
         * Gets the value of the insBoli property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getInsBoli() {
            return insBoli;
        }

        /**
         * Sets the value of the insBoli property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setInsBoli(Integer value) {
            this.insBoli = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="item" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="idType" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="idProblem" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="idItemIBS" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "item"
        })
        public static class ITEMS {

            @XmlElement(required = true)
            protected List<OperateTicket.SVRQ.ITEMS.Item> item;

            /**
             * Gets the value of the item property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the item property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link OperateTicket.SVRQ.ITEMS.Item }
             * 
             * 
             */
            public List<OperateTicket.SVRQ.ITEMS.Item> getItem() {
                if (item == null) {
                    item = new ArrayList<OperateTicket.SVRQ.ITEMS.Item>();
                }
                return this.item;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="idType" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="idProblem" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="idItemIBS" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Item {

                @XmlAttribute
                protected Integer idType;
                @XmlAttribute
                protected Integer idProblem;
                @XmlAttribute
                protected Integer count;
                @XmlAttribute
                protected String idItemIBS;

                /**
                 * Gets the value of the idType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getIdType() {
                    return idType;
                }

                /**
                 * Sets the value of the idType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setIdType(Integer value) {
                    this.idType = value;
                }

                /**
                 * Gets the value of the idProblem property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getIdProblem() {
                    return idProblem;
                }

                /**
                 * Sets the value of the idProblem property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setIdProblem(Integer value) {
                    this.idProblem = value;
                }

                /**
                 * Gets the value of the count property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getCount() {
                    return count;
                }

                /**
                 * Sets the value of the count property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setCount(Integer value) {
                    this.count = value;
                }

                /**
                 * Gets the value of the idItemIBS property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIdItemIBS() {
                    return idItemIBS;
                }

                /**
                 * Sets the value of the idItemIBS property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIdItemIBS(String value) {
                    this.idItemIBS = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="REQ">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="idReq" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="reqName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="reqLname1" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="reqLname2" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="reqCif" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="reqEmpl" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ASGTO">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="idAsg" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="idUser" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="COMM">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="lName1" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="lName2" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="inChannel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="coment" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="outChannel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="to" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="OPCOD">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="codKey1" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="codKey2" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="CLCOD">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="codKey3" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="codKey4" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="numInst" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="observ" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="codZIP" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="closeTicket" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="dataAditional" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="noteClose" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="morDebt" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="typePanel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "req",
        "asgto",
        "comm",
        "opcod",
        "clcod"
    })
    public static class TICKET {

        @XmlElement(name = "REQ", required = true)
        protected OperateTicket.TICKET.REQ req;
        @XmlElement(name = "ASGTO", required = true)
        protected OperateTicket.TICKET.ASGTO asgto;
        @XmlElement(name = "COMM", required = true)
        protected OperateTicket.TICKET.COMM comm;
        @XmlElement(name = "OPCOD", required = true)
        protected OperateTicket.TICKET.OPCOD opcod;
        @XmlElement(name = "CLCOD", required = true)
        protected OperateTicket.TICKET.CLCOD clcod;
        @XmlAttribute
        protected Integer numInst;
        @XmlAttribute
        protected String observ;
        @XmlAttribute
        protected Integer codZIP;
        @XmlAttribute
        protected Integer closeTicket;
        @XmlAttribute
        protected String dataAditional;
        @XmlAttribute
        protected String noteClose;
        @XmlAttribute
        protected Integer morDebt;
        @XmlAttribute
        protected String typePanel;

        /**
         * Gets the value of the req property.
         * 
         * @return
         *     possible object is
         *     {@link OperateTicket.TICKET.REQ }
         *     
         */
        public OperateTicket.TICKET.REQ getREQ() {
            return req;
        }

        /**
         * Sets the value of the req property.
         * 
         * @param value
         *     allowed object is
         *     {@link OperateTicket.TICKET.REQ }
         *     
         */
        public void setREQ(OperateTicket.TICKET.REQ value) {
            this.req = value;
        }

        /**
         * Gets the value of the asgto property.
         * 
         * @return
         *     possible object is
         *     {@link OperateTicket.TICKET.ASGTO }
         *     
         */
        public OperateTicket.TICKET.ASGTO getASGTO() {
            return asgto;
        }

        /**
         * Sets the value of the asgto property.
         * 
         * @param value
         *     allowed object is
         *     {@link OperateTicket.TICKET.ASGTO }
         *     
         */
        public void setASGTO(OperateTicket.TICKET.ASGTO value) {
            this.asgto = value;
        }

        /**
         * Gets the value of the comm property.
         * 
         * @return
         *     possible object is
         *     {@link OperateTicket.TICKET.COMM }
         *     
         */
        public OperateTicket.TICKET.COMM getCOMM() {
            return comm;
        }

        /**
         * Sets the value of the comm property.
         * 
         * @param value
         *     allowed object is
         *     {@link OperateTicket.TICKET.COMM }
         *     
         */
        public void setCOMM(OperateTicket.TICKET.COMM value) {
            this.comm = value;
        }

        /**
         * Gets the value of the opcod property.
         * 
         * @return
         *     possible object is
         *     {@link OperateTicket.TICKET.OPCOD }
         *     
         */
        public OperateTicket.TICKET.OPCOD getOPCOD() {
            return opcod;
        }

        /**
         * Sets the value of the opcod property.
         * 
         * @param value
         *     allowed object is
         *     {@link OperateTicket.TICKET.OPCOD }
         *     
         */
        public void setOPCOD(OperateTicket.TICKET.OPCOD value) {
            this.opcod = value;
        }

        /**
         * Gets the value of the clcod property.
         * 
         * @return
         *     possible object is
         *     {@link OperateTicket.TICKET.CLCOD }
         *     
         */
        public OperateTicket.TICKET.CLCOD getCLCOD() {
            return clcod;
        }

        /**
         * Sets the value of the clcod property.
         * 
         * @param value
         *     allowed object is
         *     {@link OperateTicket.TICKET.CLCOD }
         *     
         */
        public void setCLCOD(OperateTicket.TICKET.CLCOD value) {
            this.clcod = value;
        }

        /**
         * Gets the value of the numInst property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNumInst() {
            return numInst;
        }

        /**
         * Sets the value of the numInst property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNumInst(Integer value) {
            this.numInst = value;
        }

        /**
         * Gets the value of the observ property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObserv() {
            return observ;
        }

        /**
         * Sets the value of the observ property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObserv(String value) {
            this.observ = value;
        }

        /**
         * Gets the value of the codZIP property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCodZIP() {
            return codZIP;
        }

        /**
         * Sets the value of the codZIP property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCodZIP(Integer value) {
            this.codZIP = value;
        }

        /**
         * Gets the value of the closeTicket property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCloseTicket() {
            return closeTicket;
        }

        /**
         * Sets the value of the closeTicket property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCloseTicket(Integer value) {
            this.closeTicket = value;
        }

        /**
         * Gets the value of the dataAditional property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDataAditional() {
            return dataAditional;
        }

        /**
         * Sets the value of the dataAditional property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataAditional(String value) {
            this.dataAditional = value;
        }

        /**
         * Gets the value of the noteClose property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNoteClose() {
            return noteClose;
        }

        /**
         * Sets the value of the noteClose property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNoteClose(String value) {
            this.noteClose = value;
        }

        /**
         * Gets the value of the morDebt property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMorDebt() {
            return morDebt;
        }

        /**
         * Sets the value of the morDebt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMorDebt(Integer value) {
            this.morDebt = value;
        }

        /**
         * Gets the value of the typePanel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypePanel() {
            return typePanel;
        }

        /**
         * Sets the value of the typePanel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypePanel(String value) {
            this.typePanel = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="idAsg" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="idUser" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ASGTO {

            @XmlAttribute
            protected String idAsg;
            @XmlAttribute
            protected String idUser;

            /**
             * Gets the value of the idAsg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdAsg() {
                return idAsg;
            }

            /**
             * Sets the value of the idAsg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdAsg(String value) {
                this.idAsg = value;
            }

            /**
             * Gets the value of the idUser property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdUser() {
                return idUser;
            }

            /**
             * Sets the value of the idUser property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdUser(String value) {
                this.idUser = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="codKey3" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="codKey4" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CLCOD {

            @XmlAttribute
            protected String codKey3;
            @XmlAttribute
            protected String codKey4;

            /**
             * Gets the value of the codKey3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodKey3() {
                return codKey3;
            }

            /**
             * Sets the value of the codKey3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodKey3(String value) {
                this.codKey3 = value;
            }

            /**
             * Gets the value of the codKey4 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodKey4() {
                return codKey4;
            }

            /**
             * Sets the value of the codKey4 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodKey4(String value) {
                this.codKey4 = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="lName1" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="lName2" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="inChannel" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="coment" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="outChannel" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="to" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class COMM {

            @XmlAttribute
            protected String name;
            @XmlAttribute
            protected String lName1;
            @XmlAttribute
            protected String lName2;
            @XmlAttribute
            protected String inChannel;
            @XmlAttribute
            protected String value;
            @XmlAttribute
            protected String coment;
            @XmlAttribute
            protected String outChannel;
            @XmlAttribute
            protected Integer from;
            @XmlAttribute
            protected Integer to;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the lName1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLName1() {
                return lName1;
            }

            /**
             * Sets the value of the lName1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLName1(String value) {
                this.lName1 = value;
            }

            /**
             * Gets the value of the lName2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLName2() {
                return lName2;
            }

            /**
             * Sets the value of the lName2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLName2(String value) {
                this.lName2 = value;
            }

            /**
             * Gets the value of the inChannel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInChannel() {
                return inChannel;
            }

            /**
             * Sets the value of the inChannel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInChannel(String value) {
                this.inChannel = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the coment property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComent() {
                return coment;
            }

            /**
             * Sets the value of the coment property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComent(String value) {
                this.coment = value;
            }

            /**
             * Gets the value of the outChannel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOutChannel() {
                return outChannel;
            }

            /**
             * Sets the value of the outChannel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOutChannel(String value) {
                this.outChannel = value;
            }

            /**
             * Gets the value of the from property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getFrom() {
                return from;
            }

            /**
             * Sets the value of the from property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setFrom(Integer value) {
                this.from = value;
            }

            /**
             * Gets the value of the to property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getTo() {
                return to;
            }

            /**
             * Sets the value of the to property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTo(Integer value) {
                this.to = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="codKey1" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="codKey2" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class OPCOD {

            @XmlAttribute
            protected Integer codKey1;
            @XmlAttribute
            protected Integer codKey2;

            /**
             * Gets the value of the codKey1 property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getCodKey1() {
                return codKey1;
            }

            /**
             * Sets the value of the codKey1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setCodKey1(Integer value) {
                this.codKey1 = value;
            }

            /**
             * Gets the value of the codKey2 property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getCodKey2() {
                return codKey2;
            }

            /**
             * Sets the value of the codKey2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setCodKey2(Integer value) {
                this.codKey2 = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="idReq" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="reqName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="reqLname1" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="reqLname2" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="reqCif" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="reqEmpl" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class REQ {

            @XmlAttribute
            protected String idReq;
            @XmlAttribute
            protected String reqName;
            @XmlAttribute
            protected String reqLname1;
            @XmlAttribute
            protected String reqLname2;
            @XmlAttribute
            protected String reqCif;
            @XmlAttribute
            protected String reqEmpl;

            /**
             * Gets the value of the idReq property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdReq() {
                return idReq;
            }

            /**
             * Sets the value of the idReq property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdReq(String value) {
                this.idReq = value;
            }

            /**
             * Gets the value of the reqName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReqName() {
                return reqName;
            }

            /**
             * Sets the value of the reqName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReqName(String value) {
                this.reqName = value;
            }

            /**
             * Gets the value of the reqLname1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReqLname1() {
                return reqLname1;
            }

            /**
             * Sets the value of the reqLname1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReqLname1(String value) {
                this.reqLname1 = value;
            }

            /**
             * Gets the value of the reqLname2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReqLname2() {
                return reqLname2;
            }

            /**
             * Sets the value of the reqLname2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReqLname2(String value) {
                this.reqLname2 = value;
            }

            /**
             * Gets the value of the reqCif property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReqCif() {
                return reqCif;
            }

            /**
             * Sets the value of the reqCif property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReqCif(String value) {
                this.reqCif = value;
            }

            /**
             * Gets the value of the reqEmpl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReqEmpl() {
                return reqEmpl;
            }

            /**
             * Sets the value of the reqEmpl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReqEmpl(String value) {
                this.reqEmpl = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="idUser" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="idCountry" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="idLanguage" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="t" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class USER {

        @XmlAttribute
        protected String idUser;
        @XmlAttribute
        protected Integer idCountry;
        @XmlAttribute
        protected String idLanguage;
        @XmlAttribute
        protected String t;

        /**
         * Gets the value of the idUser property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdUser() {
            return idUser;
        }

        /**
         * Sets the value of the idUser property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdUser(String value) {
            this.idUser = value;
        }

        /**
         * Gets the value of the idCountry property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getIdCountry() {
            return idCountry;
        }

        /**
         * Sets the value of the idCountry property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setIdCountry(Integer value) {
            this.idCountry = value;
        }

        /**
         * Gets the value of the idLanguage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdLanguage() {
            return idLanguage;
        }

        /**
         * Sets the value of the idLanguage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdLanguage(String value) {
            this.idLanguage = value;
        }

        /**
         * Gets the value of the t property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getT() {
            return t;
        }

        /**
         * Sets the value of the t property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setT(String value) {
            this.t = value;
        }

    }

}
